name: $(Build.SourceBranchName)_$(Build.Reason)_$(majorVersion).$(Build.BuildId)$(Rev:.r)

trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '.\GenerateToolingFeed\GenerateToolingFeed.csproj'
    arguments: '-o  $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: false
    modifyOutputPath: false
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'