jobs:
- job: Build
  displayName: Build and publish feed generator tool

  templateContext:
    outputParentDirectory: $(Build.ArtifactStagingDirectory)
    outputs:
    - output: pipelineArtifact
      displayName: Publish bundles
      path: $(Build.ArtifactStagingDirectory)
      artifact: feed-generator

  steps:
  - task: UseDotNet@2 # The pinned SDK we use to build
    displayName: 'Install .NET SDK from global.json'
    inputs:
      packageType: sdk
      useGlobalJson: true
  - task: DotNetCoreCLI@2
    displayName: Build feed generator tool
    inputs:
      command: 'publish'
      publishWebProjects: false
      projects: '$(Build.Repository.LocalPath)/GenerateToolingFeed/*.csproj'
      arguments: '-o $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: false